version: '3.7'
services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ${APP_ROOT}:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # permission対応 macでは不要
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    user: "${UID}:${GID}"
    env_file:
      - ./.env
  composer:
    image: composer
    container_name: composer
    volumes:
      - ${APP_ROOT}:/app
      # permission対応 macでは不要
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    user: "${UID}:${GID}"
    env_file:
      - ./.env
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      -  "3306:3306"
    volumes:
      -  ./my_conf:/etc/mysql/conf.d
      -  ./logs/mysql:/var/log/mysql
      -  mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      -  "80:80"
    volumes:
      -  ${APP_ROOT}:/var/www/html
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      -  ./logs/nginx:/var/log/nginx
    env_file:
      - ./.env
    depends_on:
      -  php
      -  mysql
volumes:
  mysql-data:
